### ISSUE TITLE
ValueError: Layer weight shape (4583, 300) not compatible with provided weight shape (5804, 300)

### ISSUE THREAD

**Issue by SherryShen9** [DUT-LiuYang/Aspect-Sentiment-Analysis#1]
Hi, I got the following message when running Main.py, it seems to be the weight shape problem , any idea on solving it? thanks :
Traceback (most recent call last):
  File "Main.py", line 36, in <module>
    num_words=4582)  # 5144 4582 //   # 1523 // 1172
  File "/home/syl/Aspec-level/2018-CONLL-HAPN/Aspect-Sentiment-Analysis-master/lib/Model.py", line 63, in build_model
    sentence_embedding = sentence_embedding_layer(sentence_input)  # (?, 78, 300)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 583, in __call__
    self.set_weights(self._initial_weights)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1201, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (4583, 300) not compatible with provided weight shape (5804, 300)

**Comment by venusafroid** [comment]
你好，请问运行EmbeddingWriter.py文件时，有没有出现问题以及怎么解决的呢
